### PR TITLE
Update fontrobotmono.scss

### PR DESCRIPTION
**Pull request by produnis**
we still need "fonts" folder

### CODE REVIEW

**Comment by coatless** [comment]
@produnis that shouldn't be the case as the fonts are now being placed in the root directory when `quarto render` or `quarto preview` is called.

**Comment by coatless** [comment]
@produnis in a clean directory, I'm running in Terminal

```sh
quarto use template coatless-quarto/hsnr-revealjs
```

From there, I open up the `.qmd` file and, then, press render. I'm not seeing a missing fonts error.  

You can see a video here:

https://github.com/coatless-quarto/hsnr-revealjs/assets/833642/43c3477e-046d-45ff-b67d-f31b106d01d6

The font seems to be getting set correctly as well based on a quick look at the HTML structure:

Screenshot showing the font being set correctly in SCSS within the quarto extension

**Comment by produnis** [comment]
I did not get erros too, but you should get a Warning, that the files are not found.
Do you See any changes of the fonts in the slides when you apply my changes?

**Comment by coatless** [comment]
@produnis I'm not getting warnings from the render process or in the browser's console without `fonts`. If I add `fonts`, then I start to run into issues with the path being problematic. 

**Without applying the patch** 
Without fonts in the path screenshot of the web browser

Without fonts in the path screenshot of terminal render process

**With applying the patch**
Screenshot 2024-01-03 at 4 14 52 PM


<details>
<summary> Run summary of commands to generate presentation. </summary>

Command

```sh
quarto preview /Users/ronin/Desktop/test-hsnr/test-hsnr.qmd --n
o-browser --no-watch-inputs
```

Output

```sh
processing file: test-hsnr.qmd
1/3                  
2/3 [unnamed-chunk-1]
3/3                  
output file: test-hsnr.knit.md

pandoc 
  to: revealjs
  from: markdown-auto_identifiers+emoji
  output-file: test-hsnr.html
  standalone: true
  embed-resources: true
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML-full
  slide-level: 2
  
metadata
  link-citations: true
  width: 1050
  height: 700
  margin: 0.1
  center: false
  navigationMode: linear
  controlsLayout: edges
  controlsTutorial: false
  hash: true
  history: true
  hashOneBasedIndex: false
  fragmentInURL: false
  transition: fade
  backgroundTransition: slide
  pdfSeparateFragments: false
  lang: de
  auto-stretch: true
  theme:
    - default
    - _extensions/coatless-quarto/hsnr/HSNR.scss
    - _extensions/coatless-quarto/hsnr/fontvollkorn.scss
    - _extensions/coatless-quarto/hsnr/fontrobotmono.scss
  date-format: long
  footer: Prof. Dr. Theo Rethisch | Fachbereich 10 | Hochschule Niederrhein
  slideNumber: true
  scrollable: true
  citations-hover: true
  footnotes-hover: true
  controls: true
  hash-type: number
  hideInactiveCursor: true
  hideCursorTime: 200
  title: Demo
  bibliography:
    - literatur.bib
  
Output created: test-hsnr.html

Watching files for changes
Browse at http://localhost:5558/
```

</details>

**Comment by produnis** [comment]
thank you very much for your patiente and for explaining it to me. So, I did not get that there is a difference in wether it is a quarto extension or "just" a SCSS-Theme file. 
Thx again

**Comment by produnis** [comment]
One (other) thing I do not understand:
You activate the theme with "`format: hsnr-revealjs`".
How does quarto know where to find the files, as the subfolders are called `coatless-quarto/hsnr` and the title in `_extension.yaml` just states "`hsnr`". 
How does quarto know that "`hsnr-revealjs`" is in "`coatless-quarto/hsnr`"  ?

**Comment by coatless** [comment]
@produnis great question! So, what's happening here is Quarto's model for extensions is tied to GitHub structure. So, inside of the `_extensions/` folder on the downloaded copy of the theme, we have the location of where it was downloaded `coatless-quarto/hsnr-revealjs`. What quarto "knows" about an extension is found inside of the `_extension.yml` configuration file. In this case, we're naming the extension `hsnr` and indicating that it is contributing a `revealjs` format. Thus, when we go to use it, we need to specify `hsnr-revealjs`. The context of `-revealjs` is because an extension can have multiple formats associated with it, e.g. `-pdf`, `-pptx`, and so on.

You can read more about custom formats here: https://quarto.org/docs/extensions/formats.html#example-revealjs

**Comment by produnis** [comment]
thx again for your detailed explanation, I really appreciate it.

I dont know, but I think I like "just adding a folder" more than creating a theme. Please have a look at the "real" HSNR-Style-Template at https://github.com/produnis/real-hsnr-revealjs  (they do not have local fonts, it was just for the minimal example)
If I create a new slide for a lecture, I just copy/clone this repository and am ready to go.

**Comment by coatless** [comment]
@produnis so the setup command:

```sh
quarto use template coatless-quarto/hsnr-revealjs
```

is a thinly veiled call to `git clone` to copy the extension repository into a local directory. If you set up `ghuser/hsnr-revealjs` as a template repository, you could re-create the exact distribution method Quarto is using in a way that mirrors the "copy of a repository" approach being proposed.

With this in mind, I suppose the main benefits are just avoiding re-declaring a lot of the suboptions that you have for the theme and simplifying its use for collaborators. Plus, if you started using other Quarto extensions like your own countdown clock, then you may want to nest the extension inside the revealjs format to simplify updating in future versions. 

If you're worried about wanting to change the pre-set options, you can quickly swap out any of the default values, e.g.  by defining `footer` you've now "overridden" the extension setting for footer.

```md
---
title: A title
subtitle: A subtitle
format:
  hsnr-revealjs:
    footer: "Prof. Joe Slam | Hochschule Niederrhein"
date: last-modified
---
```

**Comment by produnis** [comment]
ok, I tried to make the "real" HSNR theme, have a look at https://github.com/produnis/hsnr-revealjs

Looks good, or?

I removed the timer, as that is now an own extension, see https://github.com/produnis/quarto-timer

**Pull request closed without merging**
